export * from './favorites/Favorites'
export * from './kids/Kids'
export * from './men/Men'
export * from './profile/Profile'
export * from './rules/Rules'
export * from './secureTransaction/SecureTransaction'
export * from './women/Women'
export * from './patternPrint/PatternPrint'
